package handler

const (
	reportBaseStyle = `<style>:root{color-scheme:light;--bg:#f3f6fb;--card:#ffffff;--ink:#142033;--muted:#5f6b7a;--line:#d8e0ec;--blue:#2156d1;--blue-soft:#e8f0ff;--red:#b42318;--amber:#b54708;--green:#067647;}*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#eef4ff 0,#f7f9fc 220px,#f3f6fb 100%);color:var(--ink)}main{max-width:1380px;margin:0 auto;padding:28px 24px 64px}h1{margin:0 0 10px;font-size:32px}h2{margin:0 0 14px;font-size:22px}p{line-height:1.6}.hero{background:linear-gradient(135deg,#17388f 0,#2156d1 52%,#4c7dff 100%);color:#fff;border-radius:20px;padding:28px;box-shadow:0 18px 50px rgba(33,86,209,.22)}.hero p{margin:6px 0 0}.hero-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:18px}.hero-stat{background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:14px}.hero-stat strong{display:block;font-size:13px;font-weight:600;opacity:.9}.hero-stat span{display:block;font-size:24px;font-weight:700;margin-top:4px}.nav{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0 4px}.nav a{text-decoration:none;color:var(--blue);background:var(--blue-soft);border:1px solid #cddcff;padding:8px 12px;border-radius:999px;font-size:13px;font-weight:600}.card{background:var(--card);border:1px solid rgba(20,32,51,.07);border-radius:18px;padding:18px 20px;margin:14px 0;box-shadow:0 10px 28px rgba(17,24,39,.06)}.section-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:12px}.section-head .hint{max-width:65%}.grid-two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.pill{display:inline-block;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:700;background:#eef2ff;color:#344054;border:1px solid #d7def5}.risk-high{color:var(--red);font-weight:700}.risk-medium{color:var(--amber);font-weight:700}.risk-low{color:var(--green);font-weight:700}table{width:100%;border-collapse:separate;border-spacing:0}th,td{border-bottom:1px solid #e5e7eb;padding:10px 12px;text-align:left;font-size:13px}th{background:#f8fafc;font-weight:700}.hint{color:var(--muted);font-size:13px}.table-wrap{overflow:auto;max-width:100%}ul{padding-left:18px}code{background:#eef2ff;padding:2px 6px;border-radius:6px}</style>`
	reportFindingsStyle = `<style>.findings-stack{display:grid;gap:16px}.finding-card{border:1px solid var(--line);border-radius:16px;background:linear-gradient(180deg,#fff 0,#f9fbff 100%);overflow:hidden}.finding-card summary{list-style:none;cursor:pointer;padding:18px 20px;display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.finding-card summary::-webkit-details-marker{display:none}.finding-card[open] summary{border-bottom:1px solid var(--line);background:#f8faff}.finding-summary-main{display:grid;gap:6px;min-width:0;flex:1}.finding-summary-side{display:grid;gap:6px;justify-items:end;text-align:right;min-width:180px}.finding-meta{display:flex;gap:8px;flex-wrap:wrap}.finding-layout{display:grid;grid-template-columns:1fr;gap:16px;padding:18px 20px}.finding-section{background:#fff;border:1px solid #e7edf7;border-radius:14px;padding:14px 16px;min-width:0;max-width:100%;overflow:hidden}.finding-section h3{margin:0 0 10px;font-size:15px}.finding-section p{margin:0 0 8px}.finding-subgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.capability-strip{display:grid;gap:10px;min-width:0;max-width:100%}.capability-card{border:1px solid #e1e8f6;border-radius:12px;background:#fbfcff;padding:12px 14px;min-width:0;max-width:100%;overflow:hidden}.capability-card *{min-width:0;max-width:100%}.capability-card p{margin:0 0 8px;overflow-wrap:anywhere;word-break:break-word}.comparison-stack{display:grid;gap:12px}.comparison-card{border:1px solid #e1e8f6;border-radius:12px;background:#fff;padding:14px 16px}.comparison-card p{margin:0 0 8px}.wide-list ul{margin-top:8px}.muted{color:var(--muted)}@media (max-width:980px){.finding-summary-side{min-width:0;justify-items:start;text-align:left}}@media (max-width:720px){.finding-card summary{flex-direction:column}.finding-subgrid{grid-template-columns:1fr}}</style>`
	reportSeverityStyle = `<style>.finding-card.severity-high{border-color:#f3b4af;box-shadow:0 14px 32px rgba(180,35,24,.10)}.finding-card.severity-high summary{background:linear-gradient(180deg,#fff5f4 0,#fff 100%)}.finding-card.severity-medium{border-color:#f8d39b;box-shadow:0 14px 32px rgba(181,71,8,.10)}.finding-card.severity-medium summary{background:linear-gradient(180deg,#fffaf0 0,#fff 100%)}.finding-card.severity-low{border-color:#b7e0c2;box-shadow:0 14px 32px rgba(6,118,71,.08)}.finding-card.severity-low summary{background:linear-gradient(180deg,#f4fff8 0,#fff 100%)}.finding-card[open].severity-high summary{background:#fff1ef}.finding-card[open].severity-medium summary{background:#fff7eb}.finding-card[open].severity-low summary{background:#eefcf3}.code-evidence{display:grid;gap:0;margin:8px 0 10px;min-width:0;max-width:100%}.code-label{padding:8px 12px;border:1px solid #24324a;border-bottom:none;border-radius:12px 12px 0 0;background:#101a2b;color:#c8d7f5;font-size:12px;font-weight:700;letter-spacing:.02em}.code-box{margin:0;border-radius:0 0 12px 12px;background:#0b1220;color:#d7e3ff;border:1px solid #24324a;padding:14px 16px;overflow:auto;line-height:1.55;max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-all}.finding-summary-side p{margin:0}.hero-stat span,.finding-summary-side,.code-label{font-variant-numeric:tabular-nums}</style>`
	reportSupplementalStyle = `<style>.source-strip{display:flex;flex-wrap:wrap;gap:8px;margin:6px 0 2px;max-width:100%}.source-strip>*{min-width:0;max-width:100%}.source-strip .pill{white-space:normal;word-break:break-word;overflow-wrap:anywhere}.pill-static{background:#eef4ff;color:#1d4ed8;border-color:#c7d7fe}.pill-dynamic{background:#ecfeff;color:#0f766e;border-color:#a5f3fc}.pill-verified{background:#f0fdf4;color:#15803d;border-color:#bbf7d0}.pill-review{background:#fff7ed;color:#c2410c;border-color:#fed7aa}.pill-fp{background:#f8fafc;color:#475467;border-color:#d0d5dd}.review-card{background:linear-gradient(180deg,#fbfcfe 0,#f6f8fc 100%);border-color:#e3e8f2}.review-card > .hint{margin-top:0}.review-task{border:1px solid #e1e7f0;border-radius:14px;background:#fff;overflow:hidden;margin-top:12px}.review-task summary{cursor:pointer;list-style:none;padding:14px 16px;font-weight:700;background:#fafcff}.review-task summary::-webkit-details-marker{display:none}.review-task[open] summary{border-bottom:1px solid #e6ebf3}.appendix-card{background:linear-gradient(180deg,#f9fbff 0,#f4f7fb 100%)}.appendix-stack{display:grid;gap:12px}.appendix-details{border:1px solid var(--line);border-radius:14px;background:#fff;overflow:hidden}.appendix-details summary{cursor:pointer;list-style:none;padding:14px 16px;font-weight:700;background:#f8fbff}.appendix-details summary::-webkit-details-marker{display:none}.appendix-details[open] summary{border-bottom:1px solid var(--line)}.appendix-body{padding:14px 16px}.appendix-body p:last-child{margin-bottom:0}</style>`
	reportPrintStyle = `<style>@media print{@page{size:A4 landscape;margin:10mm}html,body{width:100%;max-width:100%}body{background:#fff !important;zoom:.86 !important;-webkit-print-color-adjust:exact;print-color-adjust:exact}main{max-width:none;padding:0}details{display:block !important}details>summary{list-style:none !important;cursor:default !important}details>:not(summary){display:block !important}.nav{display:none !important}*{text-shadow:none !important;box-shadow:none !important}.hero,.card,.finding-card,.finding-section,.appendix-details{border:1px solid #d8e0ec !important}.card,.finding-card,.finding-section,.comparison-card,.capability-card,.review-task,.appendix-details,table,pre{break-inside:auto !important;page-break-inside:auto !important}.finding-layout,.grid-two,.finding-subgrid{grid-template-columns:1fr !important}.table-wrap{overflow:visible !important;max-width:100% !important}table{table-layout:fixed !important;width:100% !important;font-size:10px !important}th,td{word-break:break-word;overflow-wrap:anywhere;vertical-align:top}.code-box,pre,code{white-space:pre-wrap !important;word-break:break-all !important;overflow-wrap:anywhere !important;max-width:100% !important;line-height:1.4 !important;font-size:10px !important}.code-evidence{max-width:100% !important}body.pdf-compact{zoom:.80 !important}body.pdf-compact .hero{padding:16px !important}body.pdf-compact .card,body.pdf-compact .finding-card summary,body.pdf-compact .finding-layout,body.pdf-compact .finding-section,body.pdf-compact .appendix-body{padding:10px !important}body.pdf-compact table{font-size:9px !important}body.pdf-compact .code-box,body.pdf-compact pre,body.pdf-compact code{font-size:9px !important;line-height:1.3 !important}}</style>`
	reportFontStyle = `<style>body,h1,h2,h3,strong,.pill,.hero-stat span,.finding-summary-side,.code-label{font-family:"Microsoft YaHei","PingFang SC","Hiragino Sans GB","Source Han Sans SC","Noto Sans CJK SC","WenQuanYi Micro Hei","Arial Unicode MS",Segoe UI,Arial,sans-serif}.code-box{font-family:"SFMono-Regular",Consolas,"Liberation Mono","Courier New",monospace}</style>`
)

func renderReportStyles() string {
	return reportBaseStyle + reportFindingsStyle + reportSeverityStyle + reportSupplementalStyle + reportPrintStyle + reportFontStyle
}

func renderReportSupplementalStyles() string {
	return reportFindingsStyle + reportSeverityStyle + reportSupplementalStyle + reportPrintStyle + reportFontStyle
}

func renderEmbeddedPDFFontCSS(mimeType, formatHint, encodedFont string) string {
	return "<style>@font-face{font-family:'ReportCJKEmbedded';src:url(data:" + mimeType + ";base64," + encodedFont + ") format('" + formatHint + "');font-display:block;}html,body,main,section,div,p,span,strong,b,em,i,a,li,ul,ol,table,thead,tbody,tr,th,td,h1,h2,h3,h4,h5,h6,summary,details,nav,pre,code,.pill,.hero-stat span,.finding-summary-side,.code-label,.hint{font-family:'ReportCJKEmbedded' !important;} .code-box,pre,code{font-family:'ReportCJKEmbedded','SFMono-Regular',Consolas,'Liberation Mono','Courier New',monospace !important;}</style><script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('details').forEach(function(node){node.setAttribute('open','open');});var needsCompact=false;document.querySelectorAll('table').forEach(function(t){if((t.rows&&t.rows[0]&&t.rows[0].cells&&t.rows[0].cells.length>4)||t.scrollWidth>1200){needsCompact=true;}});document.querySelectorAll('pre,code').forEach(function(n){if((n.textContent||'').length>900){needsCompact=true;}});if(needsCompact){document.body.classList.add('pdf-compact');}});</script>"
}
